### ISSUE TITLE
OpenAL system fails to initialise, silent mode/no sound [arm64 Fedora Asahi, MC 1.8.9]

### ISSUE THREAD

**Issue by retropele** [Legacy-Fabric/lwjgl#3]
MC: 1.8.9
System: Fedora Asahi, arm64, M2 Macbook Pro
Java: 1.8.0_392 arm64 RH distribution
Legacy Fabric: 1.8.9-loader.0.14.22

Log: https://mclo.gs/DVUzqfc

Hi. :) I'm running Legacy Fabric on a bit of an awkward setup, but I'm having a problem I'm not sure how to fix. The issue might have something to do with this bug:

https://bugs.mojang.com/browse/MC-9974

Any help would be appreciated. Unlike the above example, I never have any sound (as opposed to sporadically). I've no idea if updating the libraries would mess up what Legacy Fabric is doing behind the scenes here (if a compatible version with the fix for my system is available).

There is no other consequence I can note except the game runs completely silently.

Thank you!

Edit: I forgot to mention this vital bit of info. Fedora Asahi does not have the speakers enabled yet for safety reasons, so this may be the cause of the bug. However, I do use headphones and these are enabled at the time of me trying to boot.

A similar error in a different java project: https://hub.jmonkeyengine.org/t/solved-exception-could-not-locate-openal-library/43423/20

**Comment by thecatcore** [comment]
Should be fixed in lastest multimc instances: https://github.com/Legacy-Fabric/multimc-instance-creator/releases

**Comment by retropele** [comment]
Hey, thank you for such a prompt fix!

I'm sorry to say it doesn't seem to have changed the situation on my end: https://mclo.gs/k61TVQd

This is my most recent attempt with the initial 14.25 fix and no other mods, but I've tried the newer file as well to no avail.

**Comment by retropele** [comment]
I hope I'm not too much bother to be commenting twice here.

I noticed the most recent update noted fixes for audio 32bit and 64bit arch, but I'm actually running arm64, not sure if this has any bearing, though?

If it has any relevance, there seems to be a fixed library for lwjgl for this problem specifically on arm64 for lwjgl2. It's from someone with a similar problem on a Raspberry Pi, but I'm too much of an idiot to know how to implement it: https://github.com/LWJGL/lwjgl/issues/158#issuecomment-852911395

Sorry to send you on a goose chase here. I know it must be finicky.

**Comment by thecatcore** [comment]
The new release contains the fix you linked already.
Your previous crash was because no openal native was shipped for arm64 Linux.
The release ships them now.
Your new crash is a different one, the native is loaded, however the sound backend (PulseAudio) refused the connection.

**Comment by retropele** [comment]
Thank you again for the help and your initial fix!

That's very helpful, I'm sure I'll be able to sort that by myself on my end. :bow:
